---
language: cpp

matrix:
  include:
    - os: Linux
      dist: focal
      arch: arm64
      env:
        - OCPN_TARGET=flatpak-arm64
        - CMAKE_BUILD_PARALLEL_LEVEL=2
      script:
        - ci/circleci-build-flatpak.sh
        - sh -c "cd build; /bin/bash < upload.sh"
        - python3 ci/git-push
    - os: osx
      osx_mage: 12.5
      env:
        - OCPN_TARGET=macos
        - CMAKE_BUILD_PARALLEL_LEVEL=2
      script:
        - ci/circleci-build-macos.sh
        - sh -c "otool -L build/app/*/OpenCPN.app/Contents/PlugIns/*.dylib"
        - sh -c "cd build; /bin/bash < upload.sh"
        - python3 ci/git-push
    - os: Linux
      dist: focal
      arch: arm64
      env:
        - OCPN_TARGET=debian-11-arm64
        - CMAKE_BUILD_PARALLEL_LEVEL=2
      script:
        - ci/generic-build-raspbian-armhf.sh
        - sh -c "cd build; /bin/bash < upload.sh"
        - python3 ci/git-push

branches:
  only:
    - travis
